# -*- coding: utf-8 -*-
"""gradecurricular.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tbnex2CiOPLqETyYcvwYA4WX_1Kqhb1M
"""

'''
Regras:

name deve ser string
name não pode estar vazio
age deve ser int
age não pode ser menor que 0
grade deve ser int ou float
grade deve estar entre 0 e 10
attendance deve ser int
attendance deve estar entre 0 e 100
Defina o status:
Nota >= 7 e presença >= 75 → "Approved"
Nota >= 5 e presença >= 75 → "Recovery"
Caso contrário → "Failed"
Defina a categoria:
idade < 13 → "Child"
idade entre 13 e 17 → "Teen"
idade >= 18 → "Adult"
Retorne:
'''

def check_student(name, age, grade, attendance):

    if not isinstance(name, str):
        return 'The student name should be a string'

    if not name:
        return 'The student should have a name'

    if not isinstance(age, int):
        return 'Age should be an integer'

    if age < 0:
        return 'Age cannot be negative'

    if not isinstance(grade, (int, float)):
        return 'Grade should be numeric'

    if grade < 0 or grade > 10:
        return 'Grade should be between 0 and 10'

    if not isinstance(attendance, int):
        return 'Attendance should be an integer'

    if attendance < 0 or attendance > 100:
        return 'Attendance should be between 0 and 100'

    if age < 13:
        category = 'Child'

    elif age <= 17:
        category = 'Teen'

    else:
        category = 'Adult'

    if grade >= 7 and attendance >= 75:
        status = 'Approved'

    elif grade >= 5 and attendance >= 75:
        status = 'Recovery'

    else:
        status = 'Failed'

    return (
        f"Student: {name}\n"
        f"Age: {age}\n"
        f"Category: {category}\n"
        f"Grade: {grade}\n"
        f"Attendance: {attendance}%\n"
        f"Status: {status}"
    )

print(check_student('Bruno',18,8.5,90))

print(check_student('Ana',15,6,80))

print(check_student('Pedro',12,4,60))

print(check_student('Joâo',18,9,100))