# -*- coding: utf-8 -*-
"""store.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tbnex2CiOPLqETyYcvwYA4WX_1Kqhb1M
"""

def check_product(name, price, stock):
    if not isinstance(name, str):
        return 'The product name should be a string'

    if not name:
        return 'The product should have a name'

    if not isinstance(price, (int, float)):
        return 'The price should be a number'

    if price < 0:
        return 'The price should not be negative'

    if not isinstance(stock, int):
        return 'The stock should be an integer'

    if stock < 0:
        return 'The stock should not be negative'

    if stock == 0:
        status = 'Out of stock'
    else:
        status = 'Available'

    return f"Product: {name}\nPrice: {price}\nStock: {stock}\nStatus: {status}"

    print(check_product('Keyboard', 120.5, 10))
print(check_product('Mouse', 50, 1))
print(check_product('headset', 20, 5))
print(check_product('Monitor', 100, 3))